### ISSUE TITLE
Safe row operations

### ISSUE THREAD

**Issue by lducas** [malb/fpylll#16]
I am trying to rerandomize basis as follows:

```
    def randomize(self, beg, end):
        for i in xrange(20):
            b = a = randint(beg,end-1)
            while b==a:
                b = randint(beg,end-1)
            assert not a==b
            s = randint(0,1)*2 -1
            with self.m.row_ops(beg,end):
                self.m.row_addmul(b, a, s)
        return
```

but this does not preserve the lattice... I'm probably using those function wrongly. Could you please specify what are the restrictions on the row operations ?

Thanks !

**Comment by malb** [comment]
It seems to me your transformation is not necessarily full rank, so maybe that's the issue? For example, `[a,b]` where `a` and `b` are rows, your code could produce `[a,a+b]` and then `[a-(a+b),b] = [-b,b]`. If that's not the issue, then I should debug this, i.e. it would seem like a bug in fpylll.

**Comment by lducas** [comment]
You are right... Thanks !
