### ISSUE TITLE
Trouble getting Gram-Schmidt norms

### ISSUE THREAD

**Issue by lducas** [malb/fpylll#2]
I have trouble getting the Gram-Schmidt norms out of those functions. I've ran beforehand :+1: 
M = GSO.Mat(B)
M.discover_all_rows()

A) getgram(i,i) gives me the norms of the vectors themselves (which is reasonable), not the GS vectors
B) sum([M.get_r(i,j)*M.get_r(i,j) for j in range(100)]) gives me 0
C) get_mu(i,i) gives me 0 as well (in some impelemntation the gram schimdt morms are stored on the dfiagonal of mu).

Could you please precise the convention of those function ? Should it be understood as those function do a decompostion B = mu * R, where mu is triangular and R orthogonal ?

**Comment by malb** [comment]
The convention for these functions should be as described here: https://github.com/dstehle/fplll/blob/master/src/gso.h

The decomposition is indeed what's being computed (from what I gather from reading gso.h/.cpp). Both `mu` and `R` are stored as lower triangular matrices. It seems, though, that those matrices are not updated ``until update_gso()`` is called.

```python
In [0]: A = IntegerMatrix(20, 20)
In [1]: A.randomize("ntrulike", bits=32, q=1456817003)
In [2]: A[0].norm()**2
5.696888852088251e+19
In [3]: M = GSO.Mat(A)
In [4]: M.get_gram(0,0)
0
In [5]: M.discover_all_rows()
In [6]: M.get_gram(0,0)
5.696888852088251e+19

In [7]: M.get_r(-1,0)
0.0
In [8]: M.get_mu(-1,0)
0.0

In [9]: M.update_gso()
True

In [10]: M.get_mu(-1,0)
0.06609622961481898
In [11]: M.get_r(-1,0)
 3.7654287365772754e+18
```

**Comment by malb** [comment]
I spent a bit more time reading fplll code and indeed,`get_r` gives you the Gram-Schmidt lengths squared and `get_mu` gives you mu.

**fpylll**

```python
In [0]: A = IntegerMatrix(6, 6)  
In [1]: A.randomize("ntrulike", bits=8, q=127)
In [2]: print A
[ 1 0 0 213 182 254 ]
[ 0 1 0 182 254 213 ]
[ 0 0 1 254 213 182 ]
[ 0 0 0 127   0   0 ]
[ 0 0 0   0 127   0 ]
[ 0 0 0   0   0 127 ]
In [3]: M = GSO.Mat(A)
In [4]: M.update_gso()
In [5]: [M.get_r(i,i) for i in range(A.nrows)]
[143010.0,
 7720.878847633023,
 5843.848156366754,
 2.759996421609685,
 2.0890108908820277,
 0.11278232291286128]

In [6]: [M.get_mu(i,i-1) for i in range(1,A.nrows)]
[0.9726312845255577,
 0.4930628912536416,
 1.2874222359909084,
 -0.4930628912546033,
 -0.972631284526287]
```

**Sage**

```python
sage: A = Matrix(ZZ, 6, 6, [[1, 0, 0, 213, 182, 254],
....:  [0, 1, 0, 182, 254, 213],
....:  [0, 0, 1, 254, 213, 182],
....:  [0, 0, 0, 127, 0, 0],
....:  [0, 0, 0, 0, 127, 0],
....:  [0, 0, 0, 0, 0, 127]]
....: )
sage: import sage.modules.misc
sage: G = sage.modules.misc.gram_schmidt(A.change_ring(RDF).rows())[0]
sage: [G[i].norm()**2 for i in range(len(G))]
[143010.0,
 7720.878847633035,
 5843.848156366755,
 2.7599964216092396,
 2.0890108908967813,
 0.1127823229144815]
sage: mu = sage.modules.misc.gram_schmidt(A.change_ring(RDF).rows())[1]
sage: [mu[i,i-1] for i in range(1,A.nrows())]
[0.9726312845255577,
 0.4930628912536415,
 1.287422235990908,
 -0.49306289125575364,
 -0.9726312845235225]
```

**Comment by lducas** [comment]
Thanks !
