### ISSUE TITLE
Release the GIL

### ISSUE THREAD

**Issue by thedrow** [malb/fpylll#21]
I noticed that the non-python operations don't release the GIL which is a shame since we could parallelize calculations if we did.

**Comment by malb** [comment]
That'd [boil down](http://docs.cython.org/src/userguide/external_C_code.html#releasing-the-gil) to a few ```with nogil``, right? Sounds like a good idea.

**Comment by thedrow** [comment]
It should, yes.

**Comment by malb** [comment]
I've tagged all C++ functions as `nogil` except for enumeration based ones which aren't threadsafe. I've also added `with nogil` for calling LLL and updating the GSO.

Based on [threads.py](https://gist.github.com/d9665068fa54123d3ee3f33dd37c76c4) it seems to work.

Overall, though, I'd say [multiprocessing](https://docs.python.org/2/library/multiprocessing.html) seems like the more appropriate choice for parallel computations: thread safety isn't an issue and copying the matrices around is negligible compared to the cost of even doing LLL. Here's an [example](https://gist.github.com/malb/1e0b55a382be4007c27d29fcc77bf6f0).

Before closing this, I'd say some documentation writing is needed.

**Comment by thedrow** [comment]
Most of the time, releasing the GIL is not about running two operations of the same kind but two different operations in parallel.
The best examples are web servers or celery workers which runs multiple threads performing many tasks. Releasing the GIL allows to increase concurrency of different jobs.

**Comment by malb** [comment]
Okay, fair enough, we shall tag everything with `nogil`, I might add some semaphores, though.

**Comment by malb** [comment]
Okay, everything tagged `nogil`, locks added for enumeration based routines and documentation added. Closing this issue as resolved now. Feel free to reopen if I overlooked something.
